### ISSUE TITLE
SZ_GetSpace: overflow on

### ISSUE THREAD

**Issue by ImmortalHostage** [dreamstalker/rehlds#185] opened 2016-03-04 04:39 UTC
http://prntscr.com/aaygy2
проблема носит массовый характер, так что я думаю разработчикам стоит обратить на это внимание. Игроки жалуются каждый день, что тупо виснет все и кикает по таймауту.

**Comment by velesgs** [comment] 2016-03-04 09:39
> [ 1] AMX Mod X RUN - amxmodx_mm_i386. v1.8.2-d ini Start ANY 
> [ 2] Reunion RUN - reunion_mm_i386. v0.1.67 ini Start Never
> [ 3] ReSemiclip RUN - resemiclip_mm_i3 v2.2(a) ini Chlvl ANY 
> [ 4] WHBlocker RUN - whblocker_mm_i38 v1.5.625 ini Chlvl ANY 
> [ 5] SRDetector RUN - srdetector_mm_i3 v1.2 ini Chlvl ANY 
> [ 6] VoiceTranscoder RUN - VoiceTranscoder. v2.0RC1 ini ANY ANY 
> [ 7] Rechecker RUN - rechecker_mm_i38 v2.0 ini Chlvl ANY 
> [ 8] FragBufFix RUN - FragBufFix.so v0.0.1 ini ANY ANY 
> [ 9] NetBufExtender RUN - nbex.so v1.0 ini ANY Never
> [10] SafeNameAndChat RUN - SafeNameAndChat. v1.0 ini ANY ANY 
> [11] Fun RUN - fun_amxx_i386.so v1.8.2-d pl1 ANY ANY 
> [12] CStrike RUN - cstrike_amxx_i38 v1.8.2-d pl1 ANY ANY 
> [13] CSX Extended RUN - csx_amxx_i386.so v1.5 pl1 ANY ANY 
> [14] ReFreeLook RUN - refreelook_amxx_ v1.3 pl1 ANY ANY 
> [15] VoiceTranscoder RUN - VoiceTranscoderA v1.0 pl1 ANY ANY 
> [16] FakeMeta RUN - fakemeta_amxx_i3 v1.8.2-d pl1 ANY ANY 
> [17] MySQL RUN - mysql_amxx_i386. v1.8.2-d pl1 ANY ANY 
> [18] Engine RUN - engine_amxx_i386 v1.8.2-d pl1 ANY ANY 
> [19] Ham Sandwich RUN - hamsandwich_amxx v1.8.2-d pl1 ANY ANY 
> 19 plugins, 19 running

мета лист

плагины

> > Currently loaded plugins:
> name version author file status 
> [ 1] unknown unknown unknown spam_block.amxx running 
> [ 2] Admin Loader 1.3.fix neygomon admin_loader_1. running 
> [ 3] fb_forwards 0.1.5 Kanagava & Realu fb_forwards.amx running 
> [ 4] AIM detector 0.9.6b kanagava aim_detector.am running 
> [ 5] AdminLogs 1.2 pirvu adminlogs.amxx running 
> [ 6] Admin Commands 1.8.2 AMXX Dev Team admincmd.amxx running 
> [ 7] Slots Reservation 1.8.2 AMXX Dev Team adminslots.amxx running 
> [ 8] Menus Front-End 1.8.2 AMXX Dev Team menufront.amxx running 
> [ 9] Commands Menu 1.8.2 AMXX Dev Team cmdmenu.amxx running 
> [ 10] Players Menu 1.8.2 AMXX Dev Team plmenu.amxx running 
> [ 11] Maps Menu 1.8.2 AMXX Dev Team mapsmenu.amxx running 
> [ 12] Admin Chat 1.8.2 AMXX Dev Team adminchat.amxx running 
> [ 13] Admin Votes 1.8.2 AMXX Dev Team adminvote.amxx running 
> [ 14] Map Manager 2.5.28 Mistrick mapmanager_v2.5 running 
> [ 15] Pause Plugins 1.8.2 AMXX Dev Team pausecfg.amxx running 
> [ 16] Stats Configuration 1.8.2 AMXX Dev Team statscfg.amxx running 
> [ 17] Restrict Weapons 1.8.2 AMXX Dev Team restmenu.amxx running 
> [ 18] CSXE Noob Entry Remove 0.2 serfreeman1337 remover_statsus running 
> [ 19] StatsX GUI 2.0 AMXX Dev Team statsx_gui.amxx running 
> [ 20] CS Stats Logging 1.8.2 AMXX Dev Team stats_logging.a running 
> [ 21] UFPS Anti Advertising 2.8 UFPS.Team antiadvert.amxx running 
> [ 22] Anti Flashbang Bug 1.0 Numb antiflashbug.am running 
> [ 23] Anti He Bug 1.1 Numb antihebug.amxx running 
> [ 24] Advert Messages 1.22 neygomon adverts.amxx running 
> [ 25] DHUD_Adverts 1.1 neygomon | edit dhud_message_de running 
> [ 26] ResetScore Final ghostrider2033 ResetScore.amxx running 
> [ 27] Descriptive 'Fire in t 0.1 VEN descriptive_fir running 
> [ 28] DemoRecoder 1.1 neygomon amx_demorec.amx running 
> [ 29] Parachute 1.0 maeStro parachute.amxx running 
> [ 30] Ping Control 1.31 neygomon Ping_Control.am running 
> [ 31] VIPka 1.34 neygomon vip_system.amxx running 
> [ 32] Advanced Gag 1.4 neygomon amx_gag.amxx running 
> [ 33] HudTextArgs Blocker 1.1 joaquimandrade hudTextArgsBloc running 
> [ 34] unknown unknown unknown set_model.amxx running 
> [ 35] Kills Counter 0.3 serfreeman1337 kills_counter.a running 
> [ 36] Game Namer 1.1 NeuroToxin gamenamechanger running 
> [ 37] Afk Control 0.5.1 neygomon afk_control.amx running 
> [ 38] UFPS AutoTeamBalance 1.4 UFPS.Team atb.amxx running 
> [ 39] UFPS TeamFlash 1.3 UFPS.Team teamflash.amxx running 
> [ 40] C4 Timer 1.4 cheap_suit c4timer.amxx running 
> [ 41] AWPoff 1.2 PAffAEJIkA :3 awp_off.amxx stopped 
> [ 42] Bet RUS 2.2 Filip Vilicic & bet_rus.amxx running 
> [ 43] Automatic knife duel 0.3 JGHG automatic_knife running 
> [ 44] No Name Change 0.1.1 VEN no_name_change. running 
> [ 45] WebHS 0.1 kanagava fb_web_online.a running 
> [ 46] FreshBan 1.1.7b kanagava fresh_bans.amxx running 
> [ 47] UFPS VoteBan 1.7 UFPS.Team voteban.amxx running 
> [ 48] Advanced Experience Sy 0.4.1 serfreeman1337 aes_main.amxx running 
> [ 49] AES: Exp CSTRIKE 0.3 serfreeman1337 aes_exp_cstrike running 
> [ 50] AES: Informer 0.2 serfreeman1337 aes_informer.am running 
> [ 51] AES: Experience Editor 0.1 serfreeman1337 aes_exp_editor. running 
> [ 52] AES: Bonus System 0.2 serfreeman1337 aes_bonus_syste running 
> [ 53] AES: Bonus CSTRIKE 0.4 serfreeman1337 aes_bonus_cstri running 
> [ 54] AES: CSTRIKE Say Tag 0.1.1 serfreeman1337 aes_say_tag.amx running 
> [ 55] AES: Status Info 0.1 serfreeman1337 aes_status_info running 
> [ 56] Lite Translit Beta 17 cv neygomon lite_translit.a running 
> [ 57] Admin Spectator ESP 1.6 KoST Admin_Spectator running 
> [ 58] Killa HP 1.6 jas0n killa_hp.amxx running 
> 58 plugins, 57 running

версия

> hostname: PatriotCS Public Ukraine | 18+
> version : 48/1.1.2.7/Stdio 690 insecure (10)
> tcp/ip : 179.60.148.36:27015
> map : awp_india at: 0 x, 0 y, 0 z
> players : 11 active (32 max)

что еще приложить?

**Comment by Adidasman1** [comment] 2016-03-04 09:45
зачем данные модули?

[ 8] FragBufFix RUN - FragBufFix.so v0.0.1 ini ANY ANY 
[ 9] NetBufExtender RUN - nbex.so v1.0 ini ANY Never

**Comment by velesgs** [comment] 2016-03-04 12:21
> sv_maxrate "100000"
> sv_minrate "20000"
> sv_maxupdaterate "102"
> sv_minupdaterate "30"
> sv_timeout "60"

так же еще
рейты рехлдс

> sv_auto_precache_sounds_in_models 1
> sv_delayed_spray_upload 1
> sv_echo_unknown_cmd 1
> sv_force_ent_intersection 1
> sv_rehlds_force_dlmax 1
> sv_rehlds_movecmdrate_max_avg 2000
> sv_rehlds_movecmdrate_max_burst 3500
> sv_rehlds_stringcmdrate_max_avg 200
> sv_rehlds_stringcmdrate_max_burst 1500


Отключение данных плагинов не помогало, тест был 24 часа, так же был оверфлов.

**Comment by Adidasman1** [comment] 2016-03-04 12:39
Попробуйте отключить те 2 модуля которые я указал выше, и выставить данные квары что я отписал ниже, потом сделать ребут. (так же протестировать при среднем онлайне, хотя бы от пол сервера, так как кол-во игроков так же зависит на переполнение.)

еще момент по поводу вх блокера, я надеюсь в сфг у вас стоит квар sndbuf = 0?

sv_minupdaterate "20"
sv_timeout "35"
sv_allowupload "0"
sv_auto_precache_sounds_in_models "0"
sv_delayed_spray_upload "0"
sv_echo_unknown_cmd "0"
sv_force_ent_intersection "0"
sv_rehlds_force_dlmax "0"

**Comment by velesgs** [comment] 2016-03-04 16:00
Сделал, ошибок меньше но все же есть. Отключил плагины что флудят в чат и рекламы.

**Comment by velesgs** [comment] 2016-03-04 16:01
онлайн 20-25

**Comment by Adidasman1** [comment] 2016-03-04 16:08
раз есть результат уже лучше, немного еще посмотреть и поискать проблемные места, далее сократиться данная проблема.

**Comment by S0m3Th1nG-AwFul** [comment] 2016-03-09 05:37
[10] SafeNameAndChat RUN - SafeNameAndChat. v1.0 ini ANY ANY 
Должен стоять на **первом месте** в метамодном plugins.ini ([первоисточник](http://cs.rin.ru/forum/viewtopic.php?f=29&t=70398)), иначе от него никакого толку и игроки будут и дальше огребать от багов с символами в чате.

**Comment by velesgs** [comment] 2016-03-20 19:24
И все равно от этой проблемы полностью не удалось избавится. По отключал все что мог.

**Comment by csportal** [comment] 2016-04-01 18:12
Проблема не в сервере,и не в его плагинах, а в глючном nbex
Уберите его оттуда, кому надо сам модулем установит.

**Comment by velesgs** [comment] 2016-04-02 04:48
да давно nbex отключил, но проблема осталась.

**Comment by csportal** [comment] 2016-04-03 20:15
Чтоб его отключить нужно его выпилить из исходников, и перекомпилить целиком rehlds.
Мой пост был адресован разработчикам.
Неизвестно зачем его туда вообще впихнули, и он сам создаёт больше проблем, чем помогает.

**Comment by Phantom-J** [comment] 2016-04-03 22:19
@csportal, why did you decide the problem is in nbex?

**Comment by csportal** [comment] 2016-06-11 17:43
Потому-что гладиолус.
На обычном hlds я его пробовал ставить модулем, и ловил аналогичные проблемы.
После его удаления всё нормализовалось.

С rehlds аналогично.
После добавления в движок начались повально таймауты у всех без исключения.

Я на 98% уверен что дело в нём. 
Если Вы считаете что это не так, берите дампы зависших клиентов, и разбирайтесь в ситуации.

**Comment by Phantom-J** [comment] 2016-06-11 19:28
@csportal, read the message above. The problem is still exists. Module off didn't decide it. You're nice advicer👏

**Comment by WPMGPRoSToTeMa** [comment] 2016-06-12 20:31
@csportal дай контакты хотя бы одного игрока, у которого это происходит постоянно.

**Comment by csportal** [comment] 2016-07-05 21:14
https://www.google.com.ua/search?ie=UTF-8&hl=ru&q=rehlds%20time%20out&gws_rd=ssl

**Comment by csportal** [comment] 2016-07-05 21:27
Reliable channel overflowed потерялся со времён 2007 года. Его поймать надо очень сильно постараться. Как бы и смысла нету расширять буфер.

Больше всего не нравиться что после добавления нбекса нельзя запускать вторую копию сервера из той же папки.
Если первая висела в фоне она 100% крашнется при смене карты.

Статистика таймаутов о чём то скажет? Сомневаюсь.
Будут крешдампы зависших клиентов, постараюсь скинуть.

**Comment by WPMGPRoSToTeMa** [comment] 2016-07-06 16:45
> Reliable channel overflowed потерялся со времён 2007 года. Его поймать надо очень сильно постараться. Как бы и смысла нету расширять буфер.

Как минимум есть одновременная смена модели игроков и смена команд в зомби модах, которая провоцирует это.

> Больше всего не нравиться что после добавления нбекса нельзя запускать вторую копию сервера из той же папки.
Если первая висела в фоне она 100% крашнется при смене карты.

У меня всё ОК на Win32.

> Статистика таймаутов о чём то скажет? Сомневаюсь.

При обрыве соединения:
- при маленьком (не расширенном) буфере клиента скорее всего выкинет с `Reliable channel overflowed`.
- при расширенном же буфере клиента скорее всего выкинет с `Timed out`, т.к. буфер просто не успевает переполниться.

Статистика должна подтвердить это.

**Comment by velesgs** [comment] 2017-01-17 20:46
Z_GetSpace: overflow on elvin
SZ_GetSpace: overflow on elvin
5.165.17.109:27005:reconnect
Dropped Xyli kto Xxyligan)))) from server
Reason:  Client sent 'drop'
176.37.97.98:27005:reconnect
SZ_GetSpace: overflow on elvin
WARNING: datagram overflowed for elvin

SZ_GetSpace: overflow on dumb
SZ_GetSpace: overflow on dumb
SZ_GetSpace: overflow on dumb
Dropped [Gyfi]_[ByProSti_ Fan] from server
Reason:  Client sent 'drop'
SZ_GetSpace: overflow on dumb
SZ_GetSpace: overflow on dumb
SZ_GetSpace: overflow on dumb
SZ_GetSpace: overflow on dumb
Dropped dumb from server
Reason:  Timed out

SZ_GetSpace: overflow on [STW] Foxxy
SZ_GetSpace: overflow on [STW] Foxxy
SZ_GetSpace: overflow on [STW] Foxxy
SZ_GetSpace: overflow on [STW] Foxxy
SZ_GetSpace: overflow on [STW] Foxxy
SZ_GetSpace: overflow on [STW] Foxxy
SZ_GetSpace: overflow on [STW] Foxxy
SZ_GetSpace: overflow on [STW] Foxxy
SZ_GetSpace: overflow on [STW] Foxxy
SZ_GetSpace: overflow on [STW] Foxxy
Dropped [STW] Foxxy from server
Reason:  Timed out
Dropped asdf from server
Reason:  Client sent 'drop'
46.39.53.116:16675:reconnect
SZ_GetSpace: overflow on asdf
SZ_GetSpace: overflow on asdf
SZ_GetSpace: overflow on asdf
Dropped C'IFR'oo' from server
Reason:  Client sent 'drop'
178.35.59.241:27005:reconnect
SZ_GetSpace: overflow on asdf
SZ_GetSpace: overflow on asdf
SZ_GetSpace: overflow on asdf
SZ_GetSpace: overflow on asdf
SZ_GetSpace: overflow on asdf
Dropped asdf from server

**Comment by velesgs** [comment] 2017-01-17 20:47
22:46:48 version
22:46:48 Protocol version 48
         Exe version 1.1.2.7/Stdio (cstrike)
         ReHLDS version: 3.0.0.396-dev
         Build date: 18:04:02 Jan 14 2017 (1008)
         Build from: https://github.com/dreamstalker/rehlds/commit/fedc99b
22:47:12 game version
22:47:12 ReGameDLL version: 5.0.0.169-dev
         Build date: 14:07:12 Jan 14 2017
         Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/faff55d
22:47:22 meta list
22:47:22 Currently loaded plugins:
               description      stat pend  file              vers      src   load  unlod
          [ 1] Reunion          RUN   -    reunion_mm_i386.  v0.1.75   ini   Start Never
          [ 2] ReAuthCheck      RUN   -    reauthcheck_mm_i  v0.1.5    ini   Start Never
          [ 3] Rechecker        RUN   -    rechecker_mm_i38  v2.3      ini   Chlvl ANY  
          [ 4] WHBlocker        RUN   -    whblocker_mm_i38  v1.5.668  ini   Chlvl ANY  
          [ 5] ReSemiclip       RUN   -    resemiclip_mm_i3  v2.3.8    ini   Chlvl ANY  
          [ 6] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.8.3-R  ini   Start ANY  
          [ 7] VoiceTranscoder  RUN   -    VoiceTranscoder.  v2017 RC  ini   ANY   ANY  
          [ 8] ReAimDetector    RUN   -    reaimdetector_am  v0.1.1    pl6   ANY   Never
          [ 9] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.8.3-R  pl6   ANY   ANY  
          [10] ReAPI            RUN   -    reapi_amxx_i386.  v5.0.0.9  pl6   ANY   Never
          [11] MySQL            RUN   -    mysql_amxx_i386.  v1.8.3-R  pl6   ANY   ANY  
          [12] FakeMeta         RUN   -    fakemeta_amxx_i3  v1.8.3-R  pl6   ANY   ANY  
          [13] Engine           RUN   -    engine_amxx_i386  v1.8.3-R  pl6   ANY   ANY  
          [14] CSX              RUN   -    csx_amxx_i386.so  v1.8.3-R  pl6   ANY   ANY  
          [15] CStrike          RUN   -    cstrike_amxx_i38  v1.8.3-R  pl6   ANY   ANY  
          [16] Fun              RUN   -    fun_amxx_i386.so  v1.8.3-R  pl6   ANY   ANY  
         16 plugins, 16 running
22:47:27 amxx list
22:47:27 Currently loaded plugins:
                name                    version     author            file             status   
          [  1] Aliases checker         1.0.3       kanagava          alias_detector.  running  
          [  2] ReChecker Logging       1.0         custom            rc_logging.amxx  running  
          [  3] HUD Message             1.5         neygomon          hud_message.amx  running  
          [  4] Admin Loader            2.6.2       neygomon          admin_loader.am  running  
          [  5] WebHS                   0.1         kanagava          fb_web_online.a  running  
          [  6] FreshBans               1.3.4       kanagava          fresh_bans_134.  running  
          [  7] DopBan                  2.9.9b      kanagava          dop_ban.amxx     running  
          [  8] AMXX BanCfg             0.95        Safety1st         amx_bancfg.amxx  running  
          [  9] unknown                 unknown     unknown           adminfreelook.a  running  
          [ 10] ScreenMaker             1.1         neygomon          screen_maker.am  running  
          [ 11] CSStatsX SQL            0.7.4       serfreeman1337    csstatsx_sql.am  running  
          [ 12] Admin Commands          1.8.3-Re    AMXX Dev Team     admincmd.amxx    running  
          [ 13] UFPS Slots Reservation  4.8         UFPS.Team         adminslots.amxx  running  
          [ 14] Menus Front-End         1.8.3-Re    AMXX Dev Team     menufront.amxx   running  
22:47:27  [ 15] Commands Menu           1.8.3-Re    AMXX Dev Team     cmdmenu.amxx     running  
          [ 16] Players Menu            1.8.3-Re    AMXX Dev Team     plmenu.amxx      running  
          [ 17] Maps Menu               1.8.3-Re    AMXX Dev Team     mapsmenu.amxx    running  
          [ 18] Plugin Menu             1.8.3-Re    AMXX Dev Team     pluginmenu.amxx  running  
          [ 19] Admin Chat              1.8.3-Re    AMXX Dev Team     adminchat.amxx   running  
          [ 20] Admin Votes             1.8.3-Re    AMXX Dev Team     adminvote.amxx   running  
          [ 21] Auto Restart            1.0         maFFyoZZyk        auto_rr.amxx     running  
          [ 22] Map Manager             2.5.61      Mistrick          mapmanager.amxx  running  
          [ 23] Mode 2x2                2.2         s1lent            mode.amxx        running  
          [ 24] Stats Configuration     1.8.3-Re    AMXX Dev Team     statscfg.amxx    running  
          [ 25] AES: StatsX             0.5 Vega    serfreeman1337    aes_statsx_cstr  running  
          [ 26] StatsX GUI              2.0         AMXX Dev Team     statsx_gui.amxx  running  
          [ 27] Steam Money Bonus       0.0.2       Vaqtincha         SteamMoneyBonus  running  
          [ 28] Player Votes            1.0         neugomon          player_votes.am  running  
          [ 29] [ReAPI] Lite TeamBalan  2.3         neugomon          lite_balancer_2  running  
22:47:27  [ 30] Advanced Gag            1.4.2       neygomon          amx_gag.amxx     running  
          [ 31] Ping Control            1.31        neygomon          Ping_Control.am  running  
          [ 32] DemoRecoder             1.1         neygomon          amx_demorec.amx  running  
          [ 33] Advanced Experience Sy  0.5 Vega    serfreeman1337    aes_main.amxx    running  
          [ 34] AES: Informer           0.5 Vega    serfreeman1337    aes_informer.am  running  
          [ 35] AES: CStrike Addon      0.5 Vega    serfreeman1337    aes_exp_cstrike  running  
          [ 36] AES: Bonus System       0.5 Vega    serfreeman1337    aes_bonus_syste  running  
          [ 37] AES: Bonus CSTRIKE      0.5 Vega    serfreeman1337    aes_bonus_cstri  running  
          [ 38] Say me and Say hp       1.4         neygomon          sayme.amxx       running  
          [ 39] UFPS TeamFlash          1.3         UFPS.Team         teamflash.amxx   running  
          [ 40] AFK Control             1.4.1 [Rnd  neygomon          afk_control.amx  running  
          [ 41] [ReAPI] Custom Models   1.6         neugomon          custom_models.a  running  
          [ 42] V.I.P Custom Weapons    1.0.0       Vaqtincha         vip_custom.amxx  running  
          [ 43] Weapon Restrict         1.7         s1lent            weapon_rest.amx  running  
          [ 44] [ReAPI] Parachute       1.1         ReHLDS Team       parachute.amxx   running  
22:47:27  [ 45] resetscore(ReAPI)       1.0         Phantom           resetscore.amxx  running  
          [ 46] WeaponState Remember    0.0.2       Vaqtincha         weaponstate_rem  running  
          [ 47] Win Messages            1.1         neygomon          win_messages.am  running  
          [ 48] say /vk by gena         0.1         GeNa              say_vk.amxx      running  
          [ 49] HudTextArgs Blocker     1.1         joaquimandrade    hudTextArgsBloc  running  
          [ 50] unknown                 unknown     unknown           no_sound.amxx    running  
          [ 51] C4 Timer on roundtime   0.3.3a      neygomon          c4timer.amxx     running  
          [ 52] Knife Duel with Telepo  1.2         neygomon          knife_duel.amxx  running  
          [ 53] AWP Limit               1.1         neugomon          awp_limit.amxx   running  
          [ 54] Kills Counter           1.0         Safety1st         killscounter.am  running  
          [ 55] Ultimate Fire in the H  1.3         OciXCrom          crx_fireintheho  running  
          [ 56] Advert Messages         1.22        neygomon          adverts.amxx     running  
          [ 57] Lite Admin ESP          1.0         neygomon          admin_esp.amxx   running  
          [ 58] Lite Translit           Beta 21     neygomon          lite_translit_1  running  
          [ 59] V.I.P Custom KNIFE      1.0.0       Vaqtincha         custom_knife.am  debug    
22:47:27  [ 60] V.I.P Custom DEAGLE     1.0.0       Vaqtincha         custom_deagle.a  debug    
          [ 61] V.I.P Custom M4A1       1.0.0       Vaqtincha         custom_m4a1.amx  debug    
          [ 62] V.I.P Custom AK-47      1.0.0       Vaqtincha         custom_ak47.amx  debug    
          [ 63] V.I.P Custom AWP        1.0.0       Vaqtincha         custom_awp.amxx  debug    
          [ 64] V.I.P Custom Famas      1.0.0       Vaqtincha         custom_famas.am  debug    
         64 plugins, 64 running
22:47:34 amxx modules
22:47:34 Currently loaded modules:
               name                    version     author               status     
          [ 1] ReAimDetector           0.1.1       ReHLDS Team          running    
          [ 2] Ham Sandwich            1.8.3-Re    AMX Mod X Dev Team   running    
          [ 3] ReAPI                   5.0.0.96-d  Asmodai & s1lent     running    
          [ 4] MySQL                   1.8.3-Re    AMX Mod X Dev Team   running    
          [ 5] FakeMeta                1.8.3-Re    AMX Mod X Dev Team   running    
          [ 6] nVault                  1.8.3-Re    AMX Mod X Dev Team   running    
          [ 7] Sockets                 1.8.3-Re    HLSW Dev Team        running    
          [ 8] Engine                  1.8.3-Re    AMX Mod X Dev Team   running    
          [ 9] CSX                     1.8.3-Re    AMX Mod X Dev Team   running    
          [10] CStrike                 1.8.3-Re    AMX Mod X Dev Team   running    
          [11] Fun                     1.8.3-Re    AMX Mod X Dev Team   running    
         11 modules, 11 correct

**Comment by velesgs** [comment] 2017-01-17 20:48
массовая проблема, когда уже решат этот баг?

**Comment by theAsmodai** [comment] 2017-01-17 20:51
It's impossible to "fix".

**Comment by WPMGPRoSToTeMa** [comment] 2017-01-18 12:02
@velesgs you need to investigate why these players lost connection. Because there are some reasons that can't be fixed:

- Player lost internet connection
- Player lost electricity
- Player closed client via `X` or `Task Manager`

But there is some reason that can be fixed: player's client was crashed. This can be problem caused by the server. But this needs additional investigations.

**Comment by velesgs** [comment] 2017-01-19 06:32
Рассказ одного из игроков.
Говорит бегаю играю, все хорошо, потом говорит кс клиент просто останавливается, и клиент вылетает либо с таймаутом, либо с переполнением канала. 
какую информацию мне предоставить? сервер на хостинге.

**Comment by WPMGPRoSToTeMa** [comment] 2017-01-19 11:03
В смысле останавливается? Клиент закрывается или что?

**Comment by BENDERJKE** [comment] 2017-01-20 16:35
Ребят я до рехлдс о этой проблеме никогда не вспоминал... А теперь жесть... 
http://www.dedicated-server.ru/vbb/showpost.php?p=298163&postcount=1118
-----
http://www.dedicated-server.ru/vbb/showpost.php?p=298174&postcount=1123

**Comment by velesgs** [comment] 2017-01-20 16:38
> В смысле останавливается? Клиент закрывается или что?
Зависает и вылетает

**Comment by BENDERJKE** [comment] 2017-01-20 18:31
Появляется критическая ошибка или просто виснет как будто серв упал, после чего ты около минуты.. не можешь зайти на сервер ( у кого как) Наверное вот это имели ввиду)

**Comment by WPMGPRoSToTeMa** [comment] 2017-01-20 19:18
> после чего ты около минуты.. не можешь зайти на сервер

А вот это уже интереснее, на другие сервера можно зайти? В консоли про бан ничего нет? Можно ли пропинговаться до сервера? Такое подозрение, что ддос протекшон на хостинге(?) шалит.

**Comment by BENDERJKE** [comment] 2017-01-20 19:52
> А вот это уже интереснее, на другие сервера можно зайти? В консоли про бан ничего нет? Можно ли пропинговаться до сервера? Такое подозрение, что ддос протекшон на хостинге(?) шалит.

На другие не пробовал, но наверное ты понимаешь о чем я, как будто соединение пропало с сервом и ты заходишь, а он типо не але.. Надо кс перезапустить и тогда все восстановится. (А тут просто подождать немного нужно)
Я спрашивал у тп на ИХ про атаки и прочее они говорят, что все в порядке...

**Comment by velesgs** [comment] 2017-01-21 10:19
Вообщем ситуация такая играю. Зависает игра, пишет конект проблемс и пипец. Клиент стим.  При этом адекватно работает, на другие сервера заходим без проблем. в момент игры в консоли отловил вот это.

> L 01/21/2017 - 13:04:17: "Marinka<242>" attacked "Alex<3<283>" with "m4a1" (damage "75") (damage_armor "16") (health "24") (armor "83")
> L 01/21/2017 - 13:04:17: "Alex<3<283>" attacked "Marinka<242>" with "famas" (damage "81") (damage_armor "17") (health "18") (armor "82")
> L 01/21/2017 - 13:04:17: "Marinka<242>" attacked "Alex<3<283>" with "m4a1" (damage "18") (damage_armor "3") (health "6") (armor "79")
> L 01/21/2017 - 13:04:18: "Marinka<242>" attacked "Alex<3<283>" with "m4a1" (damage "18") (damage_armor "3") (health "-11") (armor "75")
> L 01/21/2017 - 13:04:18: "Marinka<242>" killed "Alex<3<283>" with "m4a1"
> L 01/21/2017 - 13:04:21: "FeDyA<180>" attacked "Marinka<242>" with "awp" (damage "108") (damage_armor "0") (health "-84") (armor "81")
> L 01/21/2017 - 13:04:21: "FeDyA<180>" killed "Marinka<242>" with "awp"
> L 01/21/2017 - 13:04:29: "dezgan<241>" attacked "добрый маг<284>" with "sg552" (damage "20") (damage_armor "4") (health "79") (armor "95")
> L 01/21/2017 - 13:04:29: "dezgan<241>" attacked "FeDyA<180>" with "sg552" (damage "56") (damage_armor "12") (health "44") (armor "88")
> L 01/21/2017 - 13:04:30: "dezgan<241>" attacked "добрый маг<284>" with "sg552" (damage "25") (damage_armor "4") (health "54") (armor "90")
> SZ_GetSpace: overflow on Marinka

> SZ_GetSpace: overflow on Marinka
> Dropped Marinka from server
> Reason:  Timed out

Это повсеместное явление, через один игрок, такие проблемы.
скриншот момента https://yadi.sk/d/CtXG4C0M3A8Sru

**Comment by BENDERJKE** [comment] 2017-01-21 10:23
> Вообщем ситуация такая играю. Зависает игра, пишет конект проблемс и пипец. Клиент стим. При этом адекватно работает, на другие сервера заходим без проблем. в момент игры в консоли отловил вот это.

Какой у тебя хостинг и дц?

**Comment by velesgs** [comment] 2017-01-21 10:33
айхор и host5.ru

**Comment by BENDERJKE** [comment] 2017-01-21 12:33
Обновился до 3.0.0.402, проблема осталась =(

Dropped REVOLUTiON from server
Reason:  Client sent 'drop'
Dropped Liza from server
Reason:  Client sent 'drop'
93.78.57.74:27005:reconnect
Dropped 666 from server
Reason:  Client sent 'drop'
Dropped __aapa4i__ from server
Reason:  Client sent 'drop'

**Comment by goregore** [comment] 2017-01-25 16:44
ReHLDS version: 3.0.0.407-dev
Build date: 20:41:04 Jan 24 2017 (1018)
проблема осталась...(

Не знаю как это может помочь, но все же:
При зависании клиента у игрока(лично пробовал+со мной еще 3 игрока)
При
SZ_GetSpace: overflow on Player
WARNING: datagram overflowed for Player
Когда кс зависла в net_graph пинг 400+, я свернул прям сразу после зависания клиента и восстановил - лаг ушел) и я продолжил игру...

ps не всегда помогает сворачивание кс..

**Comment by BENDERJKE** [comment] 2017-02-21 17:52
Уже писал Теме в ЛС проблему, оставлю это еще и тут...
Появились оверфлоу без ника

> SZ_GetSpace: overflow on bab
> SZ_GetSpace: overflow on bab
> SZ_GetSpace: overflow on
> SZ_GetSpace: overflow on
> SZ_GetSpace: overflow on
> SZ_GetSpace: overflow on

**Comment by Raiz3n1312** [comment] 2017-04-09 19:59
Give more memory to server... like 800MB of ram. This is a problem. Me too suck with this problem but the memory increase solved the problem.

**Comment by In-line** [comment] 2018-02-16 14:52
Closing as non active.

**Closed by In-line** 2018-02-16 14:52 UTC

**Comment by Karaulov** [comment] 2019-11-18 15:24
@In-line  Same problem
