### ISSUE TITLE
amx_last Not Working

### ISSUE THREAD

**Issue by GoRiLliAz** [dreamstalker/rehlds#426] opened 2017-04-08 13:37 UTC
Hello,

I installed rehdsl yesterday, but I encountered a problem with amx_last this one does not show the last 10 connections.

I can not install the latest amxmodx build because it bug with this error message

L 04/08/2017 - 15:29:14: FATAL ERROR (shutting down): AbstractHookChainRegistry::addHook: The same handler can't be used twice on the hookchain.
FATAL ERROR (shutting down): AbstractHookChainRegistry::addHook: The same handler can't be used twice on the hookchain.
./hlds_run: line 255: 25546 Segmentation fault      $HL_CMD

**Comment by In-line** [comment] 2017-04-08 13:43
Install non-official reamxmodx or report bug to the amxmodx developers.

**Comment by GoRiLliAz** [comment] 2017-04-08 13:45
Hi 

I do not know how to answer on the amxmodx git there is no issue

**Comment by In-line** [comment] 2017-04-08 13:48
[Click](https://bugs.alliedmods.net/)

**Comment by In-line** [comment] 2017-04-08 13:49
Write this commands to the server console
```
meta list
game version
version
```
And show output for each of the commands.

**Comment by GoRiLliAz** [comment] 2017-04-08 13:52
I made contact with Arkshine and he is giving the link here.

**Comment by Nemesis31** [comment] 2017-04-08 15:17
Hello there,

i am with GoRiLliAz. 

Here what you asked:

**meta list**
> Currently loaded plugins:
>                description      stat pend  file              vers      src  load  unlod
>           [ 1] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.8.3-d  ini  Start ANY  
>           [ 2] NetBufExtender   RUN   -    nbex.so           v1.0      ini  ANY   Never
>           [ 3] Invalid MSG_ONE  RUN   -    msgone_blocker_a  v1.0.0-m  pl1  ANY   ANY  
>           [ 4] SteamTools       RUN   -    steamtools_amxx_  v1.1.0    pl1  ANY   ANY  
>           [ 5] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.8.3-d  pl1  ANY   ANY  
>           [ 6] FakeMeta         RUN   -    fakemeta_amxx_i3  v1.8.3-d  pl1  ANY   ANY  
>           [ 7] CStrike          RUN   -    cstrike_amxx_i38  v1.8.3-d  pl1  ANY   ANY  
>           [ 8] Fun              RUN   -    fun_amxx_i386.so  v1.8.3-d  pl1  ANY   ANY  
>           [ 9] CSX              RUN   -    csx_amxx_i386.so  v1.8.3-d  pl1  ANY   ANY  
>           [10] MySQL            RUN   -    mysql_amxx_i386.  v1.8.3-d  pl1  ANY   ANY  
>           [11] SQLite           RUN   -    sqlite_amxx_i386  v1.8.3-d  pl1  ANY   ANY  
>           [12] Engine           RUN   -    engine_amxx_i386  v1.8.3-d  pl1  ANY   ANY  
>           [13] GeoIP            RUN   -    geoip_amxx_i386.  v1.8.3-d  pl1  ANY   ANY  
>          13 plugins, 13 running

**game version**: nothing happened

**version**
> Protocol version 48
>          Exe version 1.1.2.7/Stdio (cstrike)
>          ReHLDS version: 3.0.0.518-dev
>          Build date: 20:24:57 Mar 20 2017 (1073)
>          Build from: https://github.com/dreamstalker/rehlds/commit/7e05e65

**Comment by In-line** [comment] 2017-04-08 15:22
Disable `nbef.so` it will lead to a undefined behavior and it's useless with rehlds.

**Comment by Nemesis31** [comment] 2017-04-08 15:32
I disabled the nbef.so.
Did you think it will solve the problem with amx_last ?

**Comment by Arkshine** [comment] 2017-04-08 18:45
`amx_last` code is generic and is not related to the engine. If nothing is saved, it means the `client_disconnected` forward has not been called. 

This forward is not called in the following situations;
- You have HLDS, but no gamedata is present in amxmodx/data/ or content is altered or HLDS is old.
- You have ReHLDS but API could not be instantiated, usually because you're using an old version.
Either way, it should have messages about it.

I tried also to run the latest AMXX dev version and latest ReHLDS version with the default plugins, whatever under linux or windows, I had no crash. The `amx_last` is working fine for me as well.

**Comment by GoRiLliAz** [comment] 2017-04-09 08:26
In git 5100 server start but i have this message / En git 5100 le serveur démarre mais j'ai ces problème là

```
L 04/09/2017 - 10:00:55: Binding/Hooking cvars have been disabled - check your gamedata files.
L 04/09/2017 - 10:00:55: client_disconnected and client_remove forwards have been disabled - check your gamedata files.
```

I have verified is reupload 3 times amxmodx in full with no additional plugins and always the same
J'ai vérifié et re upload 3 fois en suppriment le dossier amxmodx complétement et toujours la même chose.

`10:18:45 Currently loaded plugins:
                name                    version     author            file             status   
          [  1] Admin Base              1.8.3-dev+  AMXX Dev Team     admin.amxx       running  
          [  2] Admin Commands          1.8.3-dev+  AMXX Dev Team     admincmd.amxx    running  
          [  3] Admin Help              1.8.3-dev+  AMXX Dev Team     adminhelp.amxx   running  
          [  4] Slots Reservation       1.8.3-dev+  AMXX Dev Team     adminslots.amxx  running  
          [  5] Multi-Lingual System    1.8.3-dev+  AMXX Dev Team     multilingual.am  running  
          [  6] Menus Front-End         1.8.3-dev+  AMXX Dev Team     menufront.amxx   running  
          [  7] Commands Menu           1.8.3-dev+  AMXX Dev Team     cmdmenu.amxx     running  
          [  8] Players Menu            1.8.3-dev+  AMXX Dev Team     plmenu.amxx      running  
          [  9] Maps Menu               1.8.3-dev+  AMXX Dev Team     mapsmenu.amxx    running  
          [ 10] Plugin Menu             1.8.3-dev+  AMXX Dev Team     pluginmenu.amxx  running  
          [ 11] Admin Chat              1.8.3-dev+  AMXX Dev Team     adminchat.amxx   running  
          [ 12] Anti Flood              1.8.3-dev+  AMXX Dev Team     antiflood.amxx   running  
          [ 13] Scrolling Message       1.8.3-dev+  AMXX Dev Team     scrollmsg.amxx   running  
          [ 14] Info. Messages          1.8.3-dev+  AMXX Dev Team     imessage.amxx    running  
10:18:45  [ 15] Admin Votes             1.8.3-dev+  AMXX Dev Team     adminvote.amxx   running  
          [ 16] NextMap                 1.8.3-dev+  AMXX Dev Team     nextmap.amxx     running  
          [ 17] Nextmap Chooser         1.8.3-dev+  AMXX Dev Team     mapchooser.amxx  running  
          [ 18] TimeLeft                1.8.3-dev+  AMXX Dev Team     timeleft.amxx    running  
          [ 19] Pause Plugins           1.8.3-dev+  AMXX Dev Team     pausecfg.amxx    running  
          [ 20] Stats Configuration     1.8.3-dev+  AMXX Dev Team     statscfg.amxx    running  
          [ 21] StatsX                  1.8.3-dev+  AMXX Dev Team     statsx.amxx      running  
         21 plugins, 21 running`

```
10:19:12 Protocol version 48
         Exe version 1.1.2.7/Stdio (cstrike)
         ReHLDS version: 3.0.0.518-dev
         Build date: 20:24:57 Mar 20 2017 (1073)
         Build from: https://github.com/dreamstalker/rehlds/commit/7e05e65
```
```
10:19:57 Currently loaded plugins:
               description      stat pend  file              vers      src  load  unlod
          [ 1] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.8.3-d  ini  Start ANY  
          [ 2] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.8.3-d  pl1  ANY   ANY  
          [ 3] CSX              RUN   -    csx_amxx_i386.so  v1.8.3-d  pl1  ANY   ANY  
         3 plugins, 3 running

```
For past on rehlds I updated the file engine_i486.so y something else to do for amxmodx?
Pour passé sur rehlds j'ai mis à jours le fichier engine_i486.so y autre chose à faire pour amxmodx ?

In git 5109 i have this message 
```

L 04/09/2017 - 10:14:56: FATAL ERROR (shutting down): AbstractHookChainRegistry::addHook: The same handler can't be used twice on the hookchain.
FATAL ERROR (shutting down): AbstractHookChainRegistry::addHook: The same handler can't be used twice on the hookchain.
./hlds_run: line 255: 13945 Segmentation fault      $HL_CMD

```

**Comment by In-line** [comment] 2017-04-09 10:02
Download latest hlds from steamcmd (not 5xxx), install latest rehlds, install latest amxmodx and test it.
It's nearly impossible to install 2 same servers with same configurations and get different results.
There are 2 options for you now:

1. You didn't mention some important details. So tell us.
2. Wait.

**Comment by Arkshine** [comment] 2017-04-09 10:09
I can't reproduce using latest AMXX 1.8.3.5109 and ReHLDS 3.0.0.518-dev whatever under linux or windows.

Technically this means that the ReHLDS `registerHook` function has been used more than one time on the same hook address.

In AMXX (core), it's essentially used in `MetaAttach` called one time when metamod is ready:
- To hook `SV_DropClient` (for `client_disconnected` forward):  https://github.com/alliedmodders/amxmodx/blob/master/amxmodx/meta_api.cpp#L1639
- To Hook `Cvar_DirecSet` (for use with the new cvars stuff): https://github.com/alliedmodders/amxmodx/blob/master/amxmodx/CvarManager.cpp#L155

So:
- Crash happens a server start
- Considering you tried with default plugins and that no one uses the new cvars stuffs yet, the hook in `CvarManage.cpp` is not called. Even if it was, there is a check around to make sure it's called one time.
- What is left is the first hook, but `MetaAttach` is definitively called one time. If called more, you should see the AMXX GPL text more than one time at server start, which is not the case here right?

Well, I don't know. The only possibility is that somehow you're using the same AMXX instance more than one time, I'm not sure if it makes sense or if possible.

**Comment by GoRiLliAz** [comment] 2017-04-09 10:39
I use a single instance of amxmodx by server you know but server view arkshine you had access again in December.

so : i delete rehlds and i run git5109 and work perfectly 

@In-line My server is in latest version

**Comment by Arkshine** [comment] 2017-04-09 11:15
Looks like Metamod is forced to load twice.

**Comment by GoRiLliAz** [comment] 2017-04-09 11:19
PFFF I have host put 2 times the same sentence in the liblist.gam!

It's like this on all my servers!

With his bug rehlds but with hlds its past well.
Weird
Thanks again for your help.

**Comment by In-line** [comment] 2017-04-09 11:26
Close the issue

**Closed** 2017-04-09 11:27 UTC
