### ISSUE TITLE
When you walk up on a ramp it get's really jerky

### ISSUE THREAD

**Issue by strazdinsivars** [dreamstalker/rehlds#193] opened 2016-04-01 19:19 UTC
When i run my server same map for few hours it stars to lag when walking up ramp
I found thread with same problem, but they have no resolution
http://forums.steampowered.com/forums/showthread.php?t=142350

**Comment by theAsmodai** [comment] 2016-04-02 11:35
I think it's caused by decreasing in accuracy of `double realtime` over long time.

**Comment by In-line** [comment] 2018-02-16 15:45
Bug fix was confirmed only for HL and CS. Other mods are still in TODO state.

**Comment by WPMGPRoSToTeMa** [comment] 2018-02-16 16:31
@In-line the problem is fixed for all mods (because basically it is mode-independent), but the problem is clientdata variables that can send non-fixed gametime.

**Comment by hajimura** [comment] 2021-07-19 08:53
Should be closed as fixed

**Closed** 2021-09-11 13:28 UTC
Labels: Type: Bug, Priority: Low, Status: Available
